PDS/Controllers/homeController.cs
using Newtonsoft.Json;
using PDS.Models.Entities;
using PDS.Models.Repository;
using PDS.Models.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;

namespace PDS.Controllers
{
    public class homeController : Controller
    {
        #region Atributos Globais
            private ReturnJson objectToSerializeErr;
            private ReturnJson objectToSerializeSuc;
        #endregion

        /// <summary>
        /// Action da página home do portal.
        /// </summary>
        /// <returns>Home portal.</returns>
        [Authorize]
        public ActionResult index()
        {
            return View();
        }
  
        /// <summary>
        /// Método para enviar por email convites para usar Portal.
        /// </summary>
        /// <param name="form">FormCollection form.</param>
        [Authorize]
        [HttpPost]
        public void invitefriend(FormCollection form)
        {
            try
            {
                string email = form["email"].ToLower();

                System.Net.Mail.MailMessage mail = new System.Net.Mail.MailMessage();
                mail.To.Add(email);
                mail.From = new MailAddress("dnrevaldt@gmail.com","Portal do conhecimento");
                mail.Subject = "Mensagem do Portal";
                string Body = "<p><a href=\"http://portaldoconhecimento.com.br\"> Conheça o <b>Portal do conhecimento</b> agora! </a></p>";
                mail.Body = Body;
                mail.IsBodyHtml = true;
                SmtpClient smtp = new SmtpClient();
                smtp.Host = "smtp.gmail.com";
                smtp.Port = 587;
                smtp.UseDefaultCredentials = false;
                smtp.Credentials = new System.Net.NetworkCredential
                ("dnrevaldt@gmail.com", "letitbe10");// Enter seders User name and password
                smtp.EnableSsl = true;

                try
                {
                    smtp.Send(mail);
                    var objectToSerialize = new ReturnJson { success = true, message = "Convite enviado com sucesso para seu amigo!" };
                    Response.Write(JsonConvert.SerializeObject(objectToSerialize));
                }
                catch (Exception)
                {
                    var objectToSerialize = new ReturnJson { success = false, message = "Ops.. estamos com problemas. Verifique sua conexão e tente novamente." };
                    Response.Write(JsonConvert.SerializeObject(objectToSerialize));
                }
            }
            catch (Exception)
            {
                var objectToSerialize = new ReturnJson { success = false, message = "Ops.. estamos com problemas. Verifique sua conexão e tente novamente." };
                Response.Write(JsonConvert.SerializeObject(objectToSerialize));
            }

        }

        [HttpGet]
        public ActionResult perfil(int idperfil)
        {
            try
            {
                AccountsRepository repAccount = new AccountsRepository();
                dynamic user = repAccount.GetPerfil((Int64)idperfil);

                try
                {
                    ViewBag.idTeacherPerfil = user.idTeacher;
                }
                catch (Exception)
                {
                    ViewBag.idTeacherPerfil = null;
                }

                TempData["dataPerfilUser"] = user;

                return View("perfil");
            }
            catch (Exception)
            {
                return View("Error");
            }
            
        }

        [HttpPost]
        public void follow(FormCollection form)
        {
            if (User.Identity.IsAuthenticated)
            {
                try
                {
                    Int64 idFollower = Int64.Parse(form["idFollower"]);
                    Int64 idFollowing = Int64.Parse(form["idFollowing"]);

                    TeachersRepository repTeacher = new TeachersRepository();
                    repTeacher.Follow(idFollower, idFollowing);

                    objectToSerializeSuc = new ReturnJson { success = true, message = "", returnUrl = null, location = "" };
                    Response.Write(JsonConvert.SerializeObject(objectToSerializeSuc));
                }
                catch (Exception)
                {
                    objectToSerializeErr = new ReturnJson { success = false, message = "", returnUrl = null, location = "" };
                    Response.Write(JsonConvert.SerializeObject(objectToSerializeErr));
                }
                
            }
            else
            {
                Redirect("/site/home");
            }
        }

        [HttpPost]
        public void unfollow(FormCollection form)
        {
            if (User.Identity.IsAuthenticated)
            {
                try
                {
                    Int64 idFollower = Int64.Parse(form["idFollower"]);
                    Int64 idFollowing = Int64.Parse(form["idFollowing"]);

                    TeachersRepository repTeacher = new TeachersRepository();
                    repTeacher.UnFollow(idFollower, idFollowing);

                    objectToSerializeSuc = new ReturnJson { success = true, message = "", returnUrl = null, location = "" };
                    Response.Write(JsonConvert.SerializeObject(objectToSerializeSuc));
                }
                catch (Exception)
                {
                    objectToSerializeErr = new ReturnJson { success = false, message = "", returnUrl = null, location = "" };
                    Response.Write(JsonConvert.SerializeObject(objectToSerializeErr));
                }

            }
            else
            {
                Redirect("/site/home");
            }
        }

        [HttpPost]
        public void checkfollow(FormCollection form)
        {
            if (User.Identity.IsAuthenticated)
            {
                try
                {
                    Int64 idFollower = Int64.Parse(form["idFollower"]);
                    Int64 idFollowing = Int64.Parse(form["idFollowing"]);

                    TeachersRepository repTeacher = new TeachersRepository();
                    bool result = repTeacher.CheckFollow(idFollower, idFollowing);

                    if (result == true)
                    {
                        objectToSerializeSuc = new ReturnJson { success = true, message = "", returnUrl = null, location = "" };
                        Response.Write(JsonConvert.SerializeObject(objectToSerializeSuc));
                    }
                    else
                    {
                        objectToSerializeSuc = new ReturnJson { success = false, message = "", returnUrl = null, location = "" };
                        Response.Write(JsonConvert.SerializeObject(objectToSerializeSuc));
                    }
                    
                }
                catch (Exception)
                {
                    objectToSerializeErr = new ReturnJson { success = false, message = "Erro.", returnUrl = null, location = "" };
                    Response.Write(JsonConvert.SerializeObject(objectToSerializeErr));
                }

            }
            else
            {
                Redirect("/site/home");
            }
        }

        [HttpPost]
        public void searchteacher(FormCollection form)
        {
            if (!string.IsNullOrWhiteSpace(form["name"]))
            {
                try
                {
                    TeachersRepository repTeacher = new TeachersRepository();
                    List<Teachers> listTeacher = repTeacher.SearchTeacher(form["name"]);

                    Response.Write(JsonConvert.SerializeObject(listTeacher));
                }
                catch (Exception)
                {
                    objectToSerializeErr = new ReturnJson { success = false, message = "Error in Database.", returnUrl = null, location = "" };
                    Response.Write(JsonConvert.SerializeObject(objectToSerializeErr));
                }

            }

        }

        [HttpPost]
        public void searchstudent(FormCollection form)
        {
            if (!string.IsNullOrWhiteSpace(form["name"]))
            {
                try
                {
                    StudentsRepository repStudent = new StudentsRepository();
                    List<Students> listStudent = repStudent.SearchStudent(form["name"]);

                    Response.Write(JsonConvert.SerializeObject(listStudent));
                }
                catch (Exception)
                {
                    objectToSerializeErr = new ReturnJson { success = false, message = "Error in Database.", returnUrl = null, location = "" };
                    Response.Write(JsonConvert.SerializeObject(objectToSerializeErr));
                }

            }

        }

        [HttpPost]
        public void getfollowers(FormCollection form)
        {
            if (!string.IsNullOrWhiteSpace(form["id"]))
            {
                try
                {
                    TeachersRepository repTeacher = new TeachersRepository();
                    List<Teachers> listFollowers = repTeacher.GetFollowers(Int64.Parse(form["id"]));

                    Response.Write(JsonConvert.SerializeObject(listFollowers));
                }
                catch (Exception)
                {
                    objectToSerializeErr = new ReturnJson { success = false, message = "Error in Database.", returnUrl = null, location = "" };
                    Response.Write(JsonConvert.SerializeObject(objectToSerializeErr));
                }

            }
        }

        [HttpPost]
        public void getfollowersother(FormCollection form)
        {
            if (!string.IsNullOrWhiteSpace(form["id"]))
            {
                try
                {
                    TeachersRepository repTeacher = new TeachersRepository();

PDS/Views/Shared/KKError.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Error</title>
</head>
<body>
    <hgroup>
        <h1>Error.</h1>
        <h2>An error occurred while processing your request.</h2>
    </hgroup>
</body>
</html>

PDS/Views/Shared/_LayoutClasses.cshtml
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Denner Evaldt Machado.">
    <title>Portal do Conhecimento - @ViewBag.title</title>

    <!-- Favicon -->
    <link href="@Url.Content("~/Content/images/favicon.png")" rel="icon">

    <!-- Css -->
    @Styles.Render("~/Content/bootstrap.css")
    @Styles.Render("~/Content/home.css")
    @Scripts.Render("~/bundles/modernizr")

    <!-- Angular JS-->
    @Scripts.Render("~/Scripts/angular.js")
    @Scripts.Render("~/Scripts/app.js")
    @Scripts.Render("~/Scripts/controllers.js")
    @Scripts.Render("~/Scripts/factories.js")
    @Scripts.Render("~/Scripts/services.js")
    @Scripts.Render("~/Scripts/ngProgress.js")



    @{
        HttpCookie userInfo = Request.Cookies["userInfo"];
        var fName = Server.UrlTokenDecode(userInfo["first_name"]);
        string first_name = System.Text.UTF8Encoding.UTF8.GetString(fName);

        var Cid = Server.UrlTokenDecode(userInfo["id_account"]);
        string idAccount = System.Text.UTF8Encoding.UTF8.GetString(Cid);

        var lName = Server.UrlTokenDecode(userInfo["last_name"]);
        string last_name = System.Text.UTF8Encoding.UTF8.GetString(lName);

        var accTp = Server.UrlTokenDecode(userInfo["account_type"]);
        string account_type = System.Text.UTF8Encoding.UTF8.GetString(accTp);

        HttpCookie cookie_image = Request.Cookies["userImage"];
        var decValue = Server.UrlTokenDecode(cookie_image.Value);
        string url_image = System.Text.UTF8Encoding.UTF8.GetString(decValue);
    }

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/4.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1..2/respond.min.js"></script>
    <![endif]-->
</head>
<body ng-app="homePortal">
    <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top font-light">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="#menu-toggle" class="navbar-brand" id="menu-toggle">
                    <span class="glyphicon glyphicon-indent-left"></span>
                </a>
                <a href="/home/index" class="navbar-text">PORTAL DO CONHECIMENTO</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">

                <ul class="nav navbar-nav navbar-right">
                    @*<li class="dropdown" style="border-left: 1px solid #e2e9e6;">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                            <i class="glyphicon glyphicon-blackboard" style="line-height:30px;"></i>
                            <span class="notification-counter">3</span>
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" role="menu">
                            <li class="message-preview">
                                <a href="#">
                                    <div class="media">
                                        <div class="media-left">
                                            <span class="pull-left">
                                                <img class="media-object img-circle" src="https://scontent-lga.xx.fbcdn.net/hphotos-xpf1/v/t1.0-9/10730960_780086655387920_5666258864079525864_n.jpg?oh=1385ffe7642a1a3fe580d40488471ff5&oe=55BB3A64" alt="Image" style="width: 50px; height: 50px;">
                                            </span>
                                        </div>
                                        <div class="media-body">
                                            <h5 class="media-heading"><b>Cassio Costa</b></h5>
                                            <p>Convite de turma aceito.</p>
                                        </div>
                                    </div>
                                </a>
                                <a href="#">
                                    <div class="media">
                                        <div class="media-left">
                                            <span class="pull-left">
                                                <img class="media-object img-circle" src="https://scontent-lga.xx.fbcdn.net/hphotos-xpf1/v/t1.0-9/10730960_780086655387920_5666258864079525864_n.jpg?oh=1385ffe7642a1a3fe580d40488471ff5&oe=55BB3A64" alt="Image" style="width: 50px; height: 50px;">
                                            </span>
                                        </div>
                                        <div class="media-body">
                                            <h5 class="media-heading"><b>Cassio Costa</b></h5>
                                            <p>Convite de turma aceito.</p>
                                        </div>
                                    </div>
                                </a>
                                <a href="#">
                                    <div class="media">
                                        <div class="media-left">
                                            <span class="pull-left">
                                                <img class="media-object img-circle" src="https://scontent-lga.xx.fbcdn.net/hphotos-xpf1/v/t1.0-9/10730960_780086655387920_5666258864079525864_n.jpg?oh=1385ffe7642a1a3fe580d40488471ff5&oe=55BB3A64" alt="Image" style="width: 50px; height: 50px;">
                                            </span>
                                        </div>
                                        <div class="media-body">
                                            <h5 class="media-heading"><b>Cassio Costa</b></h5>
                                            <p>Convite de turma aceito.</p>
                                        </div>
                                    </div>
                                </a>
                            </li>
                        </ul>
                    </li>*@
                    <li class="dropdown" style="border-left: 1px solid #e2e9e6; border-right: 1px solid #e2e9e6;">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                            <img src="@url_image" alt="Image" class="img-navbar" /> @first_name <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="/home/index">Home</a></li>
                            <li class="divider"></li>
                            <li class="dropdown-header">Conta</li>
                            <li><a href="/account/manage">Gerenciar</a></li>
                            <li><a href="/account/logoff">Sair</a></li>
                        </ul>
                    </li>

                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </nav>
    <div id="wrapper" class="">
        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <div class="sidebar-brand">
                <a href="/home/perfil?idperfil=@idAccount">
                    <img src="@url_image" alt="Image" class="img-circle">
                </a>
                <h4 class="sidebar-heading">@first_name @last_name</h4>
            </div>
            <ul class="sidebar-nav">
                <li class="sidebar-heading-li">MENU</li>

                @if (account_type != "T")
                {
                    <li>
                        <a href="#"><span class="glyphicon glyphicon-user margin-rght"></span> Professores</a>
                    </li>
                    <li>
                        <a href="#"><span class="glyphicon glyphicon-duplicate margin-rght"></span> Atividades <span class="badge">0</span></a>
                    </li>
                    <li>
                        <a href="#"><span class="glyphicon glyphicon-envelope margin-rght"></span> Mensagens <span class="badge">0</span></a>
                    </li>
                }


                @if (account_type == "T")
                {
                    <li>
                        <a href="/disciplines/index"><span class="glyphicon glyphicon-folder-open margin-rght"></span> Disciplinas</a>
                    </li>
                }

            </ul>
        </div>
        <!-- /#sidebar-wrapper -->
        <!-- Page Content -->
        @RenderBody()
        <!-- /#page-content-wrapper -->
        
    </div>
    <!-- /#wrapper -->
    <!-- jQuery -->
    <script src="@Scripts.Url("~/Scripts/jquery.js")"></script>

    <!-- Menu Toggle Script -->
    <script>
        $(document).ready(function () {

            $("[data-toggle=popover]").popover();

        if (screen.width < 768){
          $("#menu-toggle").toggleClass("visibility-visible");
          $("#wrapper-right").toggleClass("toggled");
        }
        else{
          $("#menu-toggle").toggleClass("visibility-collapse");
          $("#wrapper").toggleClass("toggled");
        }
      })

      $("#menu-toggle").click(function(e) {
          e.preventDefault();
          $("#wrapper").toggleClass("toggled");
      });
    </script>

    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

</body>
</html>

PDS/Views/Shared/_LayoutManage.cshtml
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Denner Evaldt Machado.">
    <title>Portal do Conhecimento - @ViewBag.title</title>

    <!-- Favicon -->
    <link href="@Url.Content("~/Content/images/favicon.png")" rel="icon">

    <!-- Css -->
    @Styles.Render("~/Content/bootstrap.css")
    @Styles.Render("~/Content/home.css")
    @Styles.Render("~/Content/Site.css")
    @Scripts.Render("~/bundles/modernizr")

    <!-- Angular JS-->
    @Scripts.Render("~/Scripts/angular.js")
    @Scripts.Render("~/Scripts/app.js")
    @Scripts.Render("~/Scripts/controllers.js")

    <!-- jQuery -->
    <script src="@Scripts.Url("~/Scripts/jquery.js")"></script>
    @Scripts.Render("~/Scripts/jquery.form.js")


    @{
        HttpCookie userInfo = Request.Cookies["userInfo"];
        var fName = Server.UrlTokenDecode(userInfo["first_name"]);
        string first_name = System.Text.UTF8Encoding.UTF8.GetString(fName);

        var lName = Server.UrlTokenDecode(userInfo["last_name"]);
        string last_name = System.Text.UTF8Encoding.UTF8.GetString(lName);

        string idAccount = userInfo["id_account"];
        
        HttpCookie cookie_image = Request.Cookies["userImage"];
        var decValue = Server.UrlTokenDecode(cookie_image.Value);
        string url_image = System.Text.UTF8Encoding.UTF8.GetString(decValue);
    }

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/4.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1..2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top font-light">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/home/index" class="navbar-text">PORTAL DO CONHECIMENTO</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown" style="border-left: 1px solid #e2e9e6; border-right: 1px solid #e2e9e6;">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                            <img src="@url_image" alt="Image" class="img-navbar" /> @first_name <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" role="menu">
                            <li>@Html.ActionLink("Home","index","home")</li>
                            <li class="divider"></li>
                            <li class="dropdown-header">Conta</li>
                            <li><a href="/account/manage">Gerenciar</a></li>
                            <li><a href="/account/logoff">Sair</a></li>
                        </ul>
                    </li>
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </nav>
       <div class="container" ng-app="manageModule">
           @RenderBody()
       </div>

    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

</body>
</html>

PDS/Views/Shared/_LayoutNav.cshtml
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Denner Evaldt Machado.">
    <title>Portal do Conhecimento - @ViewBag.title</title>

    <!-- Favicon -->
    <link href="@Url.Content("~/Content/images/favicon.png")" rel="icon">

    <!-- Css -->
    @Styles.Render("~/Content/bootstrap.css")
    @Styles.Render("~/Content/home.css")
    @Styles.Render("~/Content/Site.css")
    @Scripts.Render("~/bundles/modernizr")

    <!-- Angular JS-->
    @Scripts.Render("~/Scripts/angular.js")
    @Scripts.Render("~/Scripts/app.js")
    @Scripts.Render("~/Scripts/controllers.js")
    @Scripts.Render("~/Scripts/factories.js")
    @Scripts.Render("~/Scripts/diretives.js")
    @Scripts.Render("~/Scripts/ngProgress.js")

    <!-- jQuery -->
    <script src="@Scripts.Url("~/Scripts/jquery.js")"></script>
    @Scripts.Render("~/Scripts/jquery.form.js")


    @{
        HttpCookie userInfo = Request.Cookies["userInfo"];
        var fName = Server.UrlTokenDecode(userInfo["first_name"]);
        string first_name = System.Text.UTF8Encoding.UTF8.GetString(fName);

        var lName = Server.UrlTokenDecode(userInfo["last_name"]);
        string last_name = System.Text.UTF8Encoding.UTF8.GetString(lName);

        string idAccount = userInfo["id_account"];
        
        HttpCookie cookie_image = Request.Cookies["userImage"];
        var decValue = Server.UrlTokenDecode(cookie_image.Value);
        string url_image = System.Text.UTF8Encoding.UTF8.GetString(decValue);
    }

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/4.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1..2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top font-light">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/home/index" class="navbar-text">PORTAL DO CONHECIMENTO</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                            <img src="@url_image" alt="Image" class="img-navbar" /> @first_name <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" role="menu">
                            <li>@Html.ActionLink("Home","index","home")</li>
                            <li class="divider"></li>
                            <li class="dropdown-header">Conta</li>
                            <li><a href="/account/manage">Gerenciar</a></li>
                            <li><a href="/account/logoff">Sair</a></li>
                        </ul>
                    </li>
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </nav>
       <div class="container">
           @RenderBody()
       </div>

    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

</body>
</html>